steps:
# pull image
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/bingsoo:base || exit 0
# build image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/base.Dockerfile',
    '-t', 'bingsoo:base',
    '-t', 'gcr.io/$PROJECT_ID/bingsoo:base',
    '--cache-from', 'gcr.io/$PROJECT_ID/bingsoo:base',
    '.'
  ]
# push image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/bingsoo:base']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/bingsoo:latest',
    '.'
  ]
coverage
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/coverage.Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/bingsoo:coverage',
    '.'
  ]
images: ['gcr.io/$PROJECT_ID/bingsoo:base', 'gcr.io/$PROJECT_ID/bingsoo:latest', 'gcr.io/$PROJECT_ID/bingsoo:coverage']
