steps:
# pull image
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/bingsoo:base || exit 0
# build image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/base.Dockerfile',
    '-t', 'bingsoo:base',
    '-t', 'gcr.io/$PROJECT_ID/bingsoo:base',
    '--cache-from', 'gcr.io/$PROJECT_ID/bingsoo:base',
    '.'
  ]
# push image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/bingsoo:base']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/bingsoo:latest',
    '.'
  ]
### COVERAGE STEP COMMENTED OUT BECAUSE FOR SOME REASON IT BREAKS THE CLOUD BUILD ####
# coverage
# - name: 'gcr.io/cloud-builders/docker'
#   args: [
#     'build',
#     '-f', 'docker/coverage.Dockerfile',
#     '-t', 'gcr.io/$PROJECT_ID/bingsoo:latest',
#     '.'
#   ]
images: ['gcr.io/$PROJECT_ID/bingsoo:base', 'gcr.io/$PROJECT_ID/bingsoo:latest']
