steps:
- name: 'Pull image'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/bingsoo:base || exit 0
- name: 'Build image'
  args: [
    'build',
    '-f', 'docker/base.Dockerfile',
    '-t', 'bingsoo:base',
    '-t', 'gcr.io/$PROJECT_ID/bingsoo:base',
    '--cache-from', 'gcr.io/$PROJECT_ID/bingsoo:base',
    '.'
  ]
- name: 'Push image'
  args: ['push', 'gcr.io/$PROJECT_ID/bingsoo:base']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/bingsoo:latest',
    '.'
  ]
# - name: 'Coverage'
#   args: [
#     'build',
#     '-f', 'docker/coverage.Dockerfile',
#     '-t', 'gcr.io/$PROJECT_ID/bingsoo:latest',
#     '.'
#   ]
images: ['gcr.io/$PROJECT_ID/bingsoo:base', 'gcr.io/$PROJECT_ID/bingsoo:latest']
